### PR TITLE
Update biolink.yaml to v2.2.x

### PR DESCRIPTION
**Pull request by tokebe**
*(addresses biothings/BioThings_Explorer_TRAPI#265)*

Replaces biolink.yaml v2.1.0 with v2.2.3.

### CODE REVIEW

**Review by andrewsu — APPROVED** [review]

**Comment by tokebe** [comment]
@andrewsu @newgene I recommend holding off on merging this PR until the following two have been merged, to avoid any conflicts (as prior to those PRs it would be necessary to update the biolink file in `bte_trapi_query_graph_handler` as well:

- biothings/bte_trapi_query_graph_handler#36
- biothings/biolink-model.js#22

**Comment by andrewsu** [comment]
Great, I reviewed all three PRs and all look pretty straightforward to me.  I propose asking @tokebe do the merge first thing tomorrow unless anyone raises any issue before then.

**Comment by newgene** [comment]
@tokebe all three PRs look good to me. Please go ahead merge them in the order as @andrewsu proposed.

**Comment by colleenXu** [comment]
How would @tokebe suggest merging the two biolink branches, so I can try testing this out? 

I tried checking out the custom_biolink branch, then doing a git merge origin/biolink_2.2.x...Then when running a query, it gave me "biolink:undefined" on the new predicate "has real world evidence of association with"

The query: 
POST to http://localhost:3000/v1/smartapi/d86a24f6027ffe778f84ba10a7a1861a/query

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e00": {
                    "subject": "n00",
                    "object": "n01"
                }
            },
            "nodes": {
                "n00": {
                    "categories": [
                        "biolink:ChemicalEntity"
                    ]
                },
                "n01": {
                    "categories": [
                        "biolink:Disease"
                    ],
                    "ids": [
                        "MONDO:0005301"
                    ]
                }
            }
        }
    }
}
```

**Comment by tokebe** [comment]
@colleenXu Checkout the `fix_issue_30` branch for the `query_graph_handler` package and try the query again. Without that branch, `query_graph_handler` loads its own biolink file which was not updated to 2.2.3 in this PR. That should solve the issue but I'm going to hold off on the merge until your confirmation.

**Comment by colleenXu** [comment]
confirmed now that it is working (probably something off with my setup earlier, and I fixed it now). 

I consider this ready to merge

**Pull request merged**
