### PR TITLE
Add support for SmallMolecule for Biolink v2.1.0 (deprecate ChemicalSubstance)

### LINKED ISSUE #15: Update entity_object handling of ChemicalSubstance to SmallMolecule for Biolink 2.1.0
As explained in biothings/BioThings_Explorer_TRAPI#207, updating to Biolink 2.1.0 causes a TypeError and crashes the instance. This is caused by [Entity](https://github.com/biothings/biolink-model.js/blob/6b4a0d723dd5f1542c2c77effe16e72e605fa187/src/object/entity_object.ts) expecting an array of strings and instead getting undefined for `id_prefixes` when its name is `ChemicalSubstance`, which is deprecated and defines no `id_prefixes`.

### PR DESCRIPTION
**Pull request by tokebe**
Replaces deprecated ChemicalSubstance case with SmallMolecule case. (addresses #15)

### CODE REVIEW

**Comment by colleenXu** [comment]
We may want to WAIT to do this....do it with the update to v2.1.0. See https://github.com/biothings/BioThings_Explorer_TRAPI/issues/207

**Comment by andrewsu** [comment]
To make it backward compatible, could we _add_ an entry for `SmallMolecule` that duplicates the current behavior for `ChemicalSubstance` and _edit_ the entry for `ChemicalSubstance` to remove the expectation of an existing array of strings?

(Also noting that this PR addresses #15.)

**Comment by tokebe** [comment]
Would it be best for ChemicalSubstance to check for an array and use it if present? e.g.
```javascript
else if (this._name === 'ChemicalSubstance') {
  this._id_prefixes = typeof idPrefixes === 'undefined' ? ['UMLS'] : [...['UMLS'], ...idPrefixes];
}
```

**Comment by andrewsu** [comment]
that seems like a very sound solution to me!

**Comment by tokebe** [comment]
Implemented and added appropriate test. Sorry, was a little over-eager to push my fix! >.<

**Pull request closed without merging**
